version: "3.8"
services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: t_apple


  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8084:8080

  spark-master:
    image: apache-spark-image:3.3.2
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    command: ["/bin/bash", "/opt/spark/scripts/start-spark.sh"]

  spark-worker-a:
    image: apache-spark-image:3.3.2
    ports:
      - "8081:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    command: ["/bin/bash", "/opt/spark/scripts/start-spark.sh"]


  spark-worker-b:
    image: apache-spark-image:3.3.2
    ports:
      - "8082:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
        - ./apps:/opt/spark-apps
        - ./data:/opt/spark-data
    command: ["/bin/bash", "/opt/spark/scripts/start-spark.sh"]


volumes:
  pg-data: